# Generated by Django 3.1.3 on 2020-11-25 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opcje_Biletu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Opcje_Biletu', models.IntegerField()),
                ('Cena', models.FloatField()),
                ('Nazwa_Biletu', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pociag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pociag', models.IntegerField()),
                ('Nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Podroze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Podroze', models.IntegerField()),
                ('Trasa', models.CharField(max_length=45)),
                ('Data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Uzytkownik', models.IntegerField()),
                ('Imie', models.CharField(max_length=45)),
                ('Nazwisko', models.CharField(max_length=45)),
                ('Login', models.CharField(max_length=45)),
                ('Haslo', models.CharField(max_length=45)),
                ('Mail', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Wagon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Wagon', models.IntegerField()),
                ('Ilosc_Miejsc', models.IntegerField()),
                ('Pociag_id_Pociag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilety.pociag')),
            ],
        ),
        migrations.CreateModel(
            name='Miejsce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Miejsce', models.IntegerField()),
                ('Numer_Miejsca', models.IntegerField()),
                ('Numer_Biletu', models.IntegerField()),
                ('Wagon_id_Wagon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilety.wagon')),
            ],
        ),
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Bilet', models.IntegerField()),
                ('Opcje_Biletu_id_Opcje_Biletu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilety.opcje_biletu')),
                ('Pociag_id_Pociag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilety.pociag')),
                ('Podroz_id_Podroz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilety.podroze')),
                ('Uzytkownik_id_Uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilety.uzytkownik')),
            ],
        ),
    ]
